#!/bin/env bash
##comment out lines by adding at least two `#' at the beginning
#SBATCH --job-name=binn
#SBATCH --account=silvestri
#SBATCH --partition=computation
#SBATCH --output=/marisdata/gerardi/%x.out
#SBATCH --error=/marisdata/gerardi/%x.err
#SBATCH --time=100-00:00:00
#SBATCH --mem=10000
#SBATCH --ntasks=8
# mail alert at start, end and abortion of execution
#SBATCH --mail-type=FAIL
# send mail to this address
#SBATCH --mail-user=francesca.gerardi@hotmail.it


mpirun -verbose -np 8 ./cosmomc test.ini > chains/chain_run_binn.log
